//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerformanceCounterWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Performance
    {
        public int Perfermance_ID { get; set; }
        public double cpu { get; set; }
        public int ram { get; set; }
        public System.DateTime timeStamp { get; set; }
        public Nullable<int> ID { get; set; }
    
        public virtual Host Host { get; set; }
    }
}
